// Old URLs that moved (UI/UX plan decisions 8, 9 and 28). Read by next.config.ts, so each
// redirect answers before any layout or guard renders, and checked by
// tests/legacy-routes.test.ts: every destination is a real page. Add to the end; never remove
// an entry, since old links and bookmarks keep arriving.
export type LegacyRedirect = { source: string; destination: string };

export const LEGACY_REDIRECTS: LegacyRedirect[] = [
    // Data retention moved to Platform admin (2026-10-01).
    { source: "/dashboard/admin/retention", destination: "/platform-admin/retention" },
    // Personal pages moved out of admin-only Settings into My account (decision 8).
    { source: "/dashboard/settings/password", destination: "/dashboard/account/security#password" },
    { source: "/dashboard/settings/mfa", destination: "/dashboard/account/security#two-factor" },
    { source: "/dashboard/settings/sessions", destination: "/dashboard/account/security#sessions" },
    // Settings regrouped under new URLs (decision 28, §11.5).
    { source: "/dashboard/settings/modules", destination: "/dashboard/settings/workspace/modules" },
    { source: "/dashboard/settings/teams", destination: "/dashboard/settings/access/teams" },
    { source: "/dashboard/settings/teams/:id", destination: "/dashboard/settings/access/teams/:id" },
    { source: "/dashboard/settings/users", destination: "/dashboard/settings/access/users" },
    { source: "/dashboard/settings/roles", destination: "/dashboard/settings/access/roles" },
    { source: "/dashboard/settings/permission-templates", destination: "/dashboard/settings/access/roles?tab=templates" },
    { source: "/dashboard/settings/sales-groups", destination: "/dashboard/settings/access/sales-groups" },
    { source: "/dashboard/settings/partners", destination: "/dashboard/settings/access/partners" },
    { source: "/dashboard/settings/partners/:id", destination: "/dashboard/settings/access/partners/:id" },
    { source: "/dashboard/settings/scim", destination: "/dashboard/settings/access/provisioning" },
    { source: "/dashboard/settings/privileged-actions", destination: "/dashboard/settings/security/approvals" },
    { source: "/dashboard/settings/governance/audit-logs", destination: "/dashboard/settings/security/audit-log" },
    { source: "/dashboard/settings/governance/gdpr", destination: "/dashboard/settings/security/privacy-requests" },
    { source: "/dashboard/settings/api-keys", destination: "/dashboard/settings/security/api-keys" },
    { source: "/dashboard/settings/custom-fields", destination: "/dashboard/settings/data/fields" },
    { source: "/dashboard/settings/lead-statuses", destination: "/dashboard/settings/data/lead-statuses" },
    { source: "/dashboard/settings/opportunity-types", destination: "/dashboard/settings/data/opportunity-types" },
    { source: "/dashboard/settings/pipelines", destination: "/dashboard/settings/data/opportunity-types" },
    { source: "/dashboard/settings/activity-types", destination: "/dashboard/settings/data/activity-types" },
    { source: "/dashboard/settings/catalog", destination: "/dashboard/settings/data/catalog" },
    { source: "/dashboard/settings/duplicate-rules", destination: "/dashboard/settings/data/duplicates" },
    { source: "/dashboard/settings/dedupe", destination: "/dashboard/settings/data/duplicates?tab=review" },
    { source: "/dashboard/settings/assignment-rules", destination: "/dashboard/settings/automation/assignment-rules" },
    { source: "/dashboard/settings/lead-scoring", destination: "/dashboard/settings/automation/lead-scoring" },
    { source: "/dashboard/settings/next-best-action", destination: "/dashboard/settings/automation/recommended-actions" },
    { source: "/dashboard/settings/task-playbooks", destination: "/dashboard/settings/automation/task-playbooks" },
    { source: "/dashboard/settings/task-sla-policies", destination: "/dashboard/settings/automation/service-levels" },
    { source: "/dashboard/settings/call-dispositions", destination: "/dashboard/settings/calling/outcomes" },
    { source: "/dashboard/settings/call-scripts", destination: "/dashboard/settings/calling/scripts" },
    { source: "/dashboard/settings/call-campaigns", destination: "/dashboard/settings/calling/campaigns" },
    { source: "/dashboard/settings/call-campaigns/:id/analytics", destination: "/dashboard/settings/calling/campaigns/:id/analytics" },
    { source: "/dashboard/settings/agent-availability", destination: "/dashboard/settings/calling/agent-capacity" },
    { source: "/dashboard/settings/service-desk", destination: "/dashboard/settings/service/desk" },
    { source: "/dashboard/settings/ai-assistant", destination: "/dashboard/settings/messaging/ai-assistant" },
    { source: "/dashboard/settings/marketplace", destination: "/dashboard/settings/integrations/marketplace" },
    { source: "/dashboard/settings/payout-cycles", destination: "/dashboard/settings/rewards/payout-cycles" },
    { source: "/dashboard/settings/commission-rules", destination: "/dashboard/settings/rewards/commission-rules" },
    { source: "/dashboard/settings/gamification", destination: "/dashboard/settings/rewards/gamification" },
    // Group URLs open the group's first page.
    { source: "/dashboard/settings/access", destination: "/dashboard/settings/access/users" },
    { source: "/dashboard/settings/security", destination: "/dashboard/settings/security/approvals" },
    { source: "/dashboard/settings/data", destination: "/dashboard/settings/data/fields" },
    { source: "/dashboard/settings/automation", destination: "/dashboard/settings/automation/assignment-rules" },
    { source: "/dashboard/settings/calling", destination: "/dashboard/settings/calling/outcomes" },
    { source: "/dashboard/settings/service", destination: "/dashboard/settings/service/desk" },
    { source: "/dashboard/settings/messaging", destination: "/dashboard/settings/messaging/ai-assistant" },
    { source: "/dashboard/settings/rewards", destination: "/dashboard/settings/rewards/payout-cycles" },
    // /dashboard/admin/* duplicated Settings pages without its menu or guard (decision 9).
    { source: "/dashboard/admin", destination: "/dashboard/settings" },
    { source: "/dashboard/admin/users", destination: "/dashboard/settings/access/users" },
    { source: "/dashboard/admin/roles", destination: "/dashboard/settings/access/roles" },
    { source: "/dashboard/admin/sales-groups", destination: "/dashboard/settings/access/sales-groups" },
    { source: "/dashboard/admin/partners", destination: "/dashboard/settings/access/partners" },
    { source: "/dashboard/admin/partners/:id", destination: "/dashboard/settings/access/partners/:id" },
    { source: "/dashboard/admin/activity-types", destination: "/dashboard/settings/data/activity-types" },
    { source: "/dashboard/admin/opportunity-types", destination: "/dashboard/settings/data/opportunity-types" },
    { source: "/dashboard/admin/pipelines", destination: "/dashboard/settings/data/opportunity-types" },
    { source: "/dashboard/admin/custom-fields", destination: "/dashboard/settings/data/fields" },
    { source: "/dashboard/admin/assignment-rules", destination: "/dashboard/settings/automation/assignment-rules" },
    { source: "/dashboard/admin/lead-scoring", destination: "/dashboard/settings/automation/lead-scoring" },
    { source: "/dashboard/admin/next-best-action", destination: "/dashboard/settings/automation/recommended-actions" },
    { source: "/dashboard/admin/commission-rules", destination: "/dashboard/settings/rewards/commission-rules" },
    { source: "/dashboard/admin/payout-cycles", destination: "/dashboard/settings/rewards/payout-cycles" },
    { source: "/dashboard/admin/gamification", destination: "/dashboard/settings/rewards/gamification" },
    { source: "/dashboard/admin/plans", destination: "/dashboard/settings/workspace/modules" },
    // Platform-only pages that sat in the tenant area (decision 9); Plans was removed (decision 35).
    { source: "/dashboard/admin/rate-limits", destination: "/platform-admin/rate-limits" },
    { source: "/dashboard/admin/usage", destination: "/platform-admin/usage" },
    { source: "/dashboard/admin/tenants", destination: "/platform-admin/tenants" },
    { source: "/dashboard/admin/security", destination: "/platform-admin/security-policies" },
    // Reports regrouped (decision 30): the group URL opens its first page.
    { source: "/dashboard/settings/analytics", destination: "/dashboard/settings/analytics/annotations" },
];
