// Real catalog data mirrored from apps/unnatividya/src/data/catalog.ts (arjunharish77/crm-new@main)
export const universities = [
  { id:'muj', slug:'manipal-university-jaipur', name:'Manipal University Jaipur', shortName:'MUJ', city:'Jaipur, Rajasthan', established:2011, rating:4.7, reviews:3240, learners:'52,000+', approvals:['UGC-entitled','NAAC A+','AICTE','WES recognised'], placement:88, avgPackage:'₹7.2 LPA', highestPackage:'₹24 LPA', partners:320, feeFrom:'₹75,000', img:'assets/muj-campus.webp', logo:'assets/muj-logo.svg',
    about:'Manipal University Jaipur brings the Manipal education legacy to flexible online degrees with digital learning support, placement assistance, and recognised programs for working learners.' },
  { id:'smu', slug:'sikkim-manipal-university', name:'Sikkim Manipal University', shortName:'SMU', city:'Gangtok, Sikkim', established:1995, rating:4.5, reviews:2110, learners:'38,000+', approvals:['UGC-entitled','NAAC A+','AIU member'], placement:81, avgPackage:'₹5.1 LPA', highestPackage:'₹15 LPA', partners:210, feeFrom:'₹55,000', img:'assets/smu-campus.webp', logo:'assets/smu-logo.svg',
    about:'Sikkim Manipal University offers affordable online UG and PG degrees with flexible schedules, learner support, and a practical path for students and working professionals.' },
  { id:'amity', slug:'amity-online', name:'Amity University Online', shortName:'Amity', city:'Noida, Uttar Pradesh', established:2005, rating:4.4, reviews:4870, learners:'85,000+', approvals:['UGC-entitled','NAAC A+','WES recognised','QS ranked'], placement:84, avgPackage:'₹6.5 LPA', highestPackage:'₹21 LPA', partners:400, feeFrom:'₹99,000', img:'assets/amity-campus.webp', logo:'assets/amity-logo.svg',
    about:'Amity Online offers UGC-entitled online degrees with flexible learning, industry-oriented curriculum, and a large alumni and learner network.' }
];

const C = (id,slug,uni,name,short,level,stream,duration,fee,emi,rating,reviews,specs,eligibility,roles) =>
  ({ id, slug, universityId:uni, name, shortName:short, level, stream, duration, fee, emi, rating, reviews, specializations:specs, eligibility, careerRoles:roles });

export const courses = [
  C('mba-muj','online-mba-manipal-university-jaipur','muj','Online MBA','MBA','PG','Management','24 months',180000,'₹7,500/mo',4.7,1420,['Finance','Marketing','Human Resource Management','Analytics & Data Science','Operations Management','IT & FinTech','Information System Management','Project Management','International Business','Supply Chain Management','BFSI','Retail Management','Digital Marketing'],"Bachelor's degree (10+2+3) in any discipline with a minimum of 50% marks (45% for reserved categories). No work experience or entrance test required.",['Business Manager','Marketing Manager','Finance Analyst','Operations Lead']),
  C('mba-smu','online-mba-sikkim-manipal-university','smu','Online MBA','MBA','PG','Management','24 months',120000,'₹4,583/mo',4.5,860,['Marketing','Finance','HR','Systems','Operations & Supply Chain Management','Healthcare'],"Bachelor's degree (10+2+3/4) in any discipline with a minimum of 50% marks (45% for reserved categories). Dual specialization: choose any 2 of 6 tracks.",['Team Lead','Sales Manager','HR Executive','Retail Operations Manager']),
  C('mba-amity','online-mba-amity-online','amity','Online MBA','MBA','PG','Management','24 months',225000,'₹9,375/mo',4.4,2210,['Business Analytics','Data Science','Digital Marketing Management','Entrepreneurship and Leadership Management','Finance and Accounting Management','Human Resource Management','Information Technology Management','International Business Management','International Finance (ACCA)','Marketing & Sales Management','Production and Operations Management','Hospital and Healthcare Management','Construction Project Management','General Management'],"Bachelor's degree in any discipline with a minimum of 40% marks (an internal eligibility test is available for below 40%). No work experience or entrance test required.",['Product Manager','Business Analyst','Marketing Strategist','International Business Executive']),
  C('bba-muj','online-bba-manipal-university-jaipur','muj','Online BBA','BBA','UG','Management','36 months',139500,'₹3,875/mo',4.6,640,['Human Resource Management','Marketing','Finance & Accounting','Entrepreneurship Management & Family Business','Data Analytics','Retail & E-Commerce','Digital Marketing'],'10+2 or equivalent from a recognised board.',['Business Associate','Sales Executive','Marketing Associate','Operations Coordinator']),
  C('bba-smu','online-bba-sikkim-manipal-university','smu','Online BBA','BBA','UG','Management','36 months',90000,'₹2,500/mo',4.6,420,['Business Analytics & FinTech','Entrepreneurship','Operations & Supply Chain Management','Banking & Insurance'],'10+2 or equivalent from a recognised board.',['Business Associate','Sales Executive','Marketing Associate','Operations Coordinator']),
  C('bba-amity','online-bba-amity-online','amity','Online BBA','BBA','UG','Management','36 months',199000,'₹8,292/mo',4.3,910,['Data Analytics','Travel and Tourism Management'],'10+2 or equivalent from a recognised board.',['Management Trainee','Retail Associate','Sales Executive','Customer Success Associate']),
  C('bca-muj','online-bca-manipal-university-jaipur','muj','Online BCA','BCA','UG','IT & Computers','36 months',139500,'₹3,875/mo',4.6,730,['Data Science & Analytics','Cloud Computing','Cybersecurity'],'10+2 or equivalent from a recognised board, any stream. Mathematics is not a mandatory subject.',['Software Developer','Web Developer','Cloud Support Associate','QA Analyst']),
  C('bca-amity','online-bca-amity-online','amity','Online BCA','BCA','UG','IT & Computers','36 months',175000,'₹7,292/mo',4.3,820,['Fintech & AI','Data Engineering','Software Engineering','Data Analytics','Cloud & Security','Data Science'],'10+2 or equivalent from a recognised board, any stream. Mathematics/Computer Science/Informatics Practices are preferred but not mandatory.',['Software Developer','Data Analyst','Technical Support Engineer','Database Assistant']),
  C('mca-muj','online-mca-manipal-university-jaipur','muj','Online MCA','MCA','PG','IT & Computers','24 months',158000,'₹6,583/mo',4.7,560,['AI and Data Science','Cloud Computing','Cybersecurity','Comprehensive Emerging Technologies','AI and ML'],"Bachelor's degree, any discipline (50% marks, 45% reserved). A compulsory mathematics/computing bridge course applies in Semester 1 if not studied at 10+2 or graduation.",['Full Stack Developer','Data Engineer','Cybersecurity Analyst','Application Developer']),
  C('mca-smu','online-mca-sikkim-manipal-university','smu','Online MCA','MCA','PG','IT & Computers','24 months',110000,'₹4,083/mo',4.6,410,['AI & Machine Learning','Data Science','Cloud Computing','Cyber Security'],"Bachelor's degree in Computer Applications/CS/IT preferred; a compulsory bridge course in computing fundamentals applies if not studied at 10+2 or graduation.",['Software Developer','Systems Analyst','Database Assistant','Technical Support Engineer']),
  C('mca-amity','online-mca-amity-online','amity','Online MCA','MCA','PG','IT & Computers','24 months',199000,'₹8,292/mo',4.4,690,['Fintech & AI','Machine Learning & Artificial Intelligence','Cyber Security','Software Engineering','Blockchain Technology & Management'],"BCA, or a bachelor's degree (Science/Commerce/Arts) with Mathematics, or a B.Tech/BE in a CS-related field. A qualifying bridge course applies if Mathematics wasn't studied at 10+2 or graduation.",['Machine Learning Associate','Cloud Engineer','Software Engineer','Systems Analyst']),
  C('bcom-muj','online-bcom-manipal-university-jaipur','muj','Online B.Com','B.Com','UG','Commerce','36 months',99000,'₹2,750/mo',4.5,480,['Accounting with AI','Banking & FinTech','Business Accounting & Taxation','Business Analytics','Digital Marketing with AI','E-Commerce','Economics','Financial Analytics'],'10+2 or equivalent from a recognised board.',['Account Executive','Finance Associate','Tax Assistant','Audit Assistant']),
  C('bcom-smu','online-bcom-sikkim-manipal-university','smu','Online B.Com','B.Com','UG','Commerce','36 months',75000,'₹2,083/mo',4.4,350,['General'],'10+2 or equivalent from a recognised board.',['Accounts Assistant','Finance Executive','Banking Associate','Tax Associate']),
  C('bcom-amity','online-bcom-amity-online','amity','Online B.Com','B.Com','UG','Commerce','36 months',115000,'₹4,792/mo',4.4,760,['International Finance & Accounting'],'10+2 or equivalent from a recognised board.',['Account Executive','Finance Associate','Tax Assistant','Audit Assistant']),
  C('bcom-honours-amity','online-bcom-honours-amity-online','amity','Online B.Com Honours','B.Com Honours','UG','Commerce','36 months',175000,'₹7,292/mo',4.3,240,['International Business','Business Data Processing','Marketing Management','HRM','Entrepreneurship Development','Spreadsheet Modelling in Business','E-Commerce & its Applications','ACCA Track'],'10+2 or equivalent from a recognised board with a minimum of 55% marks.',['Account Executive','Finance Associate','Tax Assistant','Audit Assistant']),
  C('mcom-muj','online-mcom-manipal-university-jaipur','muj','Online M.Com','M.Com','PG','Commerce','24 months',108000,'₹4,500/mo',4.6,290,['General'],'Graduation in commerce or related discipline as per university criteria.',['Finance Manager','Accountant','Tax Consultant','Fintech Associate']),
  C('mcom-smu','online-mcom-sikkim-manipal-university','smu','Online M.Com','M.Com','PG','Commerce','24 months',75000,'₹3,125/mo',4.4,260,['Finance','Marketing'],'Graduation in commerce or related discipline as per university criteria.',['Accountant','Finance Executive','Tax Consultant','Banking Associate']),
  C('mcom-amity','online-mcom-amity-online','amity','Online M.Com','M.Com','PG','Commerce','24 months',150000,'₹6,250/mo',4.4,310,['Financial Management','Financial Technology'],'Graduation in commerce or related discipline as per university criteria.',['Finance Manager','Accountant','Tax Consultant','Fintech Associate']),
  C('ba-smu','online-ba-sikkim-manipal-university','smu','Online BA','BA','UG','Arts & Humanities','36 months',75000,'₹2,083/mo',4.4,310,['English','Political Science','Sociology'],'10+2 or equivalent from a recognised board.',['Content Associate','Public Policy Assistant','Research Assistant','Civil Services Aspirant']),
  C('ba-amity','online-ba-amity-online','amity','Online BA','BA','UG','Arts & Humanities','36 months',115000,'₹4,792/mo',4.3,260,['Sociology','Political Science','English','Economics','Hindi Medium','Kannada Medium','Malayalam Medium','Tamil Medium','Telugu Medium'],'10+2 or equivalent from a recognised board.',['Content Associate','Public Policy Assistant','Research Assistant','Civil Services Aspirant']),
  C('bajmc-amity','online-ba-journalism-mass-communication-amity-online','amity','Online BA JMC','BA JMC','UG','Arts & Humanities','36 months',190000,'₹7,917/mo',4.3,190,['General'],'10+2 or equivalent from a recognised board.',['Journalist','Content Strategist','PR Executive','Media Planner']),
  C('ma-english-smu','online-ma-english-sikkim-manipal-university','smu','Online MA English','MA English','PG','Arts & Humanities','24 months',75000,'₹3,125/mo',4.4,210,['General'],'Graduation from a recognised university.',['Content Strategist','Teacher','Editor','Research Associate']),
  C('ma-political-science-smu','online-ma-political-science-sikkim-manipal-university','smu','Online MA Political Science','MA Political Science','PG','Arts & Humanities','24 months',75000,'₹3,125/mo',4.4,190,['General'],'Graduation from a recognised university.',['Policy Assistant','Research Associate','Civil Services Aspirant','Public Affairs Associate']),
  C('ma-sociology-smu','online-ma-sociology-sikkim-manipal-university','smu','Online MA Sociology','MA Sociology','PG','Arts & Humanities','24 months',75000,'₹3,125/mo',4.5,180,['General'],'Graduation from a recognised university.',['Social Researcher','Program Associate','Policy Assistant','Community Manager']),
  C('ma-economics-muj','online-ma-economics-manipal-university-jaipur','muj','Online MA Economics','MA Economics','PG','Arts & Humanities','24 months',80000,'₹3,333/mo',4.2,170,['General'],'Graduation from a recognised university.',['Economic Analyst','Research Associate','Policy Assistant','Data Analyst']),
  C('majmc-muj','online-ma-journalism-mass-communication-manipal-university-jaipur','muj','Online MA JMC','MA JMC','PG','Arts & Humanities','24 months',80000,'₹3,333/mo',4.5,220,['General'],'Graduation from a recognised university.',['Journalist','Content Strategist','PR Executive','Media Planner']),
  C('majmc-amity','online-ma-journalism-mass-communication-amity-online','amity','Online MA JMC','MA JMC','PG','Arts & Humanities','24 months',130000,'₹5,417/mo',4.3,240,['Journalism & Mass Communication'],'Graduation from a recognised university.',['Journalist','Content Strategist','PR Executive','Media Planner']),
  C('ma-public-policy-governance-amity','online-ma-public-policy-governance-amity-online','amity','Online MA Public Policy & Governance','MA Public Policy','PG','Arts & Humanities','24 months',150000,'₹6,250/mo',4.2,110,['Leadership and Administrative Thinkers','Economics and Public Policy','Urban and Rural Development in India'],'Graduation from a recognised university.',['Policy Assistant','Program Associate','Civil Services Aspirant','Research Associate']),
  C('msc-data-science-amity','online-msc-data-science-amity-online','amity','Online MSc Data Science','MSc Data Science','PG','IT & Computers','24 months',275000,'₹11,458/mo',4.4,150,['General'],"Bachelor's degree in any Science discipline — not restricted to computer science, mathematics, or statistics specifically.",['Data Scientist','Machine Learning Engineer','Data Analyst','Data Engineer']),
  C('msc-mathematics-muj','online-msc-mathematics-manipal-university-jaipur','muj','Online MSc Mathematics','MSc Mathematics','PG','IT & Computers','24 months',80000,'₹3,333/mo',4.6,130,['Mathematics','Data Science','Computational Science','Econometrics'],'A BSc degree, or a 10+2+3/4-year bachelor\u2019s degree with Mathematics as a compulsory subject.',['Data Analyst','Statistician','Actuary','Research Associate'])
];

export const universityById = Object.fromEntries(universities.map(u => [u.id, u]));
export const courseById = Object.fromEntries(courses.map(c => [c.id, c]));
export const streams = ['Management','IT & Computers','Commerce','Arts & Humanities'];

export const roleSalary = {
  'Business Manager':'₹6-11 LPA','Business Analyst':'₹5-9 LPA','Marketing Manager':'₹7-14 LPA','Marketing Strategist':'₹6-12 LPA','Finance Analyst':'₹5-10 LPA','Finance Manager':'₹8-15 LPA','Operations Lead':'₹8-15 LPA','Operations Coordinator':'₹4-7 LPA','Product Manager':'₹9-18 LPA','International Business Executive':'₹6-11 LPA','Team Lead':'₹6-10 LPA','Sales Manager':'₹6-11 LPA','Sales Executive':'₹3-6 LPA','HR Executive':'₹4-7 LPA','Retail Operations Manager':'₹5-9 LPA','Business Associate':'₹3-6 LPA','Management Trainee':'₹3-5 LPA','Retail Associate':'₹2.5-4.5 LPA','Customer Success Associate':'₹3-6 LPA','Marketing Associate':'₹3-5 LPA',
  'Software Developer':'₹4-10 LPA','Web Developer':'₹3-8 LPA','Cloud Support Associate':'₹4-8 LPA','Cloud Engineer':'₹7-16 LPA','QA Analyst':'₹4-8 LPA','Data Analyst':'₹5-11 LPA','Data Engineer':'₹6-13 LPA','Technical Support Engineer':'₹3-6 LPA','Database Assistant':'₹3-6 LPA','Full Stack Developer':'₹6-14 LPA','Cybersecurity Analyst':'₹6-13 LPA','Application Developer':'₹5-11 LPA','Machine Learning Associate':'₹7-15 LPA','Systems Analyst':'₹5-10 LPA','Software Engineer':'₹6-13 LPA',
  'Account Executive':'₹3-6 LPA','Finance Associate':'₹3-6 LPA','Tax Assistant':'₹3-5 LPA','Audit Assistant':'₹3-6 LPA','Accounts Assistant':'₹2.5-5 LPA','Finance Executive':'₹4-7 LPA','Banking Associate':'₹3-6 LPA','Tax Associate':'₹3-6 LPA','Accountant':'₹3-7 LPA','Tax Consultant':'₹5-10 LPA','Fintech Associate':'₹5-10 LPA',
  'Content Associate':'₹3-6 LPA','Public Policy Assistant':'₹3-6 LPA','Research Assistant':'₹3-5 LPA','Civil Services Aspirant':'Cadre-based pay','Content Strategist':'₹5-10 LPA','Teacher':'₹3-7 LPA','Editor':'₹4-8 LPA','Research Associate':'₹3-6 LPA','Social Researcher':'₹3-6 LPA','Program Associate':'₹3-6 LPA','Community Manager':'₹4-7 LPA','Policy Assistant':'₹3-6 LPA','Economic Analyst':'₹5-10 LPA','Journalist':'₹3-7 LPA','PR Executive':'₹3-6 LPA','Media Planner':'₹4-8 LPA','Public Affairs Associate':'₹3-6 LPA',
  'Data Scientist':'₹6-14 LPA','Machine Learning Engineer':'₹8-16 LPA','Statistician':'₹5-10 LPA','Actuary':'₹7-15 LPA'
};

export const approvalIcon = label => {
  const L = label.toUpperCase();
  if (L.includes('UGC')) return 'assets/ap-ugc.svg';
  if (L.includes('NAAC')) return 'assets/ap-naac.svg';
  if (L.includes('AICTE')) return 'assets/ap-aicte.svg';
  if (L.includes('WES')) return 'assets/ap-wes.svg';
  if (L.includes('AIU')) return 'assets/ap-aiu.svg';
  return null;
};

export const fmtFee = v => '₹' + v.toLocaleString('en-IN');

export const curriculumByStream = {
  'Management':[['Semester 1',['Management principles','Business communication','Financial accounting','Managerial economics','Organisational behaviour']],['Semester 2',['Marketing management','Human resource management','Operations management','Business research','Financial management']],['Semester 3',['Strategic management','Elective track subjects','Analytics / domain modules','Project or term paper']],['Semester 4',['Advanced electives','Capstone project','Entrepreneurship','Industry application']]],
  'IT & Computers':[['Semester 1',['Programming fundamentals','Computer organisation','Mathematics for computing','Database basics']],['Semester 2',['Data structures','Operating systems','Web technologies','Object-oriented programming']],['Semester 3',['Software engineering','Cloud / security fundamentals','Data analytics','Project work']],['Semester 4',['Advanced development','Elective track','Capstone project','Industry application']]],
  'Commerce':[['Semester 1',['Financial accounting','Business economics','Business organisation','Commercial law']],['Semester 2',['Cost accounting','Business statistics','Corporate accounting','Taxation basics']],['Semester 3',['Corporate finance','Auditing','Investment management','Elective modules']],['Semester 4',['Advanced accounting','Research/project work','Financial markets','Career electives']]],
  'Arts & Humanities':[['Semester 1',['Foundation concepts','Academic writing','Research orientation','Core discipline paper']],['Semester 2',['Core discipline paper','Indian/global context','Skill-based paper','Elective module']],['Semester 3',['Advanced discipline paper','Research methods','Elective module','Project preparation']],['Semester 4',['Advanced electives','Dissertation/project','Career application','Seminar paper']]]
};

export const blogPosts = [
  { slug:'is-online-mba-valid-for-government-jobs', cat:'Validity', title:'Is an online MBA valid for government jobs?', excerpt:'What UGC entitlement legally means for recruitment, and the one document to verify before you enrol.', read:'6 min read', img:'assets/blog-govt-jobs.webp' },
  { slug:'best-online-mba-working-professionals', cat:'Programs', title:'Best online MBA for working professionals', excerpt:'Weekend live classes, EMI plans and specialisation depth compared across MUJ, SMU and Amity.', read:'8 min read', img:'assets/blog-best-mba.webp' },
  { slug:'online-bca-after-12th-guide', cat:'Programs', title:'Online BCA after 12th: a complete guide', excerpt:'Eligibility without Mathematics, fee bands, and which specialisation actually leads to a developer job.', read:'7 min read', img:'assets/blog-bca.webp' },
  { slug:'wes-evaluation-online-degrees', cat:'Validity', title:'WES evaluation of Indian online degrees', excerpt:'How MUJ and Amity online degrees are assessed for work and masters programs abroad.', read:'5 min read', img:'assets/blog-wes.webp' },
  { slug:'online-admission-documents-checklist', cat:'Admissions', title:'Documents checklist for online admission', excerpt:'Everything from mark sheets to bank statements for education loans, and common rejection reasons.', read:'4 min read', img:'assets/blog-documents.webp' },
  { slug:'mca-vs-mba-it-careers', cat:'Careers', title:'MCA vs MBA for IT careers: which pays better?', excerpt:'Role trajectories and salary bands, and how recruiters read each degree on a resume.', read:'7 min read', img:'assets/blog-mca-mba.webp' }
];
