import { describe,it,expect } from 'vitest';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
async function simulate({drift=false,missing=false,repair}:{drift?:boolean;missing?:boolean;repair?:'objects-missing'|'objects-present'}={}){
 const calls:Array<{sql:string,args?:unknown[]}>=[];let failure:unknown;
 const client={query:async(sql:string,args?:unknown[])=>{calls.push({sql,args});if(sql.includes('pg_try_advisory_lock'))return {rows:[{acquired:true}]};if(sql.includes('as tenant'))return {rows:[missing?{}:{tenant:'Tenant',ledger:'SchemaMigration'}]};if(repair&&sql.includes('as present'))return {rows:[{present:repair==='objects-present'}]};if(repair&&sql.includes('select "checksum"')&&args?.[0]==='0020_advanced_predictive_scoring.sql')return {rowCount:1,rows:[{checksum:'new',status:'APPLIED'}]};if(sql.includes('select "checksum"'))return drift?{rowCount:1,rows:[{checksum:'old',status:'APPLIED'}]}:{rowCount:0,rows:[]};return {rowCount:0,rows:[]};}};
 const sandbox={require:(name:string)=>name==='fs'?{readFileSync:(file:string)=> `ALTER TABLE fixture_${path.basename(String(file),'.sql')} ADD COLUMN upgraded boolean;`}:name==='path'?path:name==='child_process'?{spawnSync:()=>{throw new Error('Bootstrap must never run during upgrade');}}:name==='./db-utils'?{appDatabaseUrl:()=> 'postgresql://app@localhost/test',directDatabaseUrl:()=> 'postgresql://admin@localhost/test',roleNameFromUrl:()=> 'app',quoteIdentifier:(s:string)=>`"${s}"`,checksum:()=> 'new',withClient:async(_:unknown,fn:(c:typeof client)=>Promise<void>)=>fn(client),ensureMigrationTable:()=>{throw new Error('Must not create a migration ledger in upgrade mode');},migrationFiles:()=> repair?['0020_advanced_predictive_scoring.sql','0116_test.sql']:['0116_test.sql']}:undefined,process:{env:{BASE_SCHEMA_SQL_PATH:'base-schema.sql'},argv:['node','script','--upgrade'],exit:()=>undefined},console:{log:()=>undefined,error:(e:unknown)=>{failure=e;}}};
 vm.runInNewContext(fs.readFileSync('scripts/db-migrate-local.js','utf8'),sandbox);await new Promise(resolve=>setTimeout(resolve,10));return {calls,failure};
}
describe('safe existing-database upgrade',()=>{
 it('runs pending SQL with a configured base path without baseline or role escalation',async()=>{const {calls,failure}=await simulate();expect(failure).toBeUndefined();expect(calls.some(c=>c.sql.startsWith('ALTER TABLE fixture'))).toBe(true);expect(calls.some(c=>/drop schema|bypassrls|alter schema.*owner/i.test(c.sql))).toBe(false);});
 it('refuses checksum drift without overwriting the ledger',async()=>{const {calls,failure}=await simulate({drift:true});expect(String(failure)).toContain('checksum changed');expect(calls.some(c=>c.sql.startsWith('ALTER TABLE fixture'))).toBe(false);});
 it('refuses a missing database or ledger rather than bootstrapping',async()=>{const {calls,failure}=await simulate({missing:true});expect(String(failure)).toContain('Upgrade requires');expect(calls.some(c=>c.sql.startsWith('ALTER TABLE fixture'))).toBe(false);});
 it('re-runs a baselined-but-never-executed migration before pending ones',async()=>{const {calls,failure}=await simulate({repair:'objects-missing'});expect(failure).toBeUndefined();const order=calls.map(c=>c.sql).filter(q=>q.startsWith('ALTER TABLE fixture'));expect(order).toEqual(['ALTER TABLE fixture_0020_advanced_predictive_scoring ADD COLUMN upgraded boolean;','ALTER TABLE fixture_0116_test ADD COLUMN upgraded boolean;']);});
 it('leaves a genuinely applied migration alone',async()=>{const {calls,failure}=await simulate({repair:'objects-present'});expect(failure).toBeUndefined();expect(calls.some(c=>c.sql.startsWith('ALTER TABLE fixture_0020'))).toBe(false);});
});
