-- Gap checklist: "Add password and authentication policy controls for non-SSO users."
-- SecurityPolicy's password fields (minPasswordLength/requireUppercase/.../passwordExpiryDays/
-- preventPasswordReuse) already existed and were editable via the admin UI, but nothing ever
-- read them -- this migration adds the schema real enforcement needs.

-- Anchor for password-expiry checks (SecurityPolicy.passwordExpiryDays) -- backfilled to
-- "createdAt" for existing rows so nobody's password looks freshly-changed the moment this
-- ships (which would silently reset everyone's expiry clock to "just now").
alter table "User" add column if not exists "passwordChangedAt" timestamptz;
update "User" set "passwordChangedAt" = "createdAt" where "passwordChangedAt" is null;
alter table "User" alter column "passwordChangedAt" set default now();

-- Reuse prevention (SecurityPolicy.preventPasswordReuse): every password a user has ever set,
-- bcrypt-hashed same as the live "User"."password" column -- never the plaintext.
create table if not exists "PasswordHistory" (
  id text primary key,
  "userId" text not null references "User"(id),
  "tenantId" text references "Tenant"(id),
  "passwordHash" text not null,
  "createdAt" timestamptz not null default now()
);
create index if not exists "PasswordHistory_user_idx" on "PasswordHistory" ("userId", "createdAt" desc);

-- Admin-initiated password reset: this app has no system/transactional email sender (only a
-- tenant-configurable marketing-communications pipeline gated behind an admin-configured
-- provider, wrong tool for a security-critical reset link) -- so a reset token is generated by
-- a tenant admin and copied/shared with the user manually, the same manual-communication
-- convention this app already uses for a new user's temporary password at invite time. Hashed
-- the same way MFA backup codes/trusted-device tokens are (never store the raw token).
create table if not exists "PasswordResetToken" (
  id text primary key,
  "userId" text not null references "User"(id),
  "tenantId" text references "Tenant"(id),
  "tokenHash" text not null,
  "expiresAt" timestamptz not null,
  "usedAt" timestamptz,
  "createdBy" text,
  "createdAt" timestamptz not null default now()
);
create index if not exists "PasswordResetToken_user_idx" on "PasswordResetToken" ("userId", "createdAt" desc);
