export const careerRoleSalary: Record<string, string> = {
  // Management
  "Business Manager": "₹6-11 LPA",
  "Business Analyst": "₹5-9 LPA",
  "Marketing Manager": "₹7-14 LPA",
  "Marketing Strategist": "₹6-12 LPA",
  "Finance Analyst": "₹5-10 LPA",
  "Finance Manager": "₹8-15 LPA",
  "Operations Lead": "₹8-15 LPA",
  "Operations Coordinator": "₹4-7 LPA",
  "Product Manager": "₹9-18 LPA",
  "International Business Executive": "₹6-11 LPA",
  "Team Lead": "₹6-10 LPA",
  "Sales Manager": "₹6-11 LPA",
  "Sales Executive": "₹3-6 LPA",
  "HR Executive": "₹4-7 LPA",
  "Retail Operations Manager": "₹5-9 LPA",
  "Business Associate": "₹3-6 LPA",
  "Management Trainee": "₹3-5 LPA",
  "Retail Associate": "₹2.5-4.5 LPA",
  "Customer Success Associate": "₹3-6 LPA",
  "Marketing Associate": "₹3-5 LPA",
  // IT & Computers
  "Software Developer": "₹4-10 LPA",
  "Web Developer": "₹3-8 LPA",
  "Cloud Support Associate": "₹4-8 LPA",
  "Cloud Engineer": "₹7-16 LPA",
  "QA Analyst": "₹4-8 LPA",
  "Data Analyst": "₹5-11 LPA",
  "Data Engineer": "₹6-13 LPA",
  "Technical Support Engineer": "₹3-6 LPA",
  "Database Assistant": "₹3-6 LPA",
  "Full Stack Developer": "₹6-14 LPA",
  "Cybersecurity Analyst": "₹6-13 LPA",
  "Application Developer": "₹5-11 LPA",
  "Machine Learning Associate": "₹7-15 LPA",
  "Systems Analyst": "₹5-10 LPA",
  "Software Engineer": "₹6-13 LPA",
  // Commerce
  "Account Executive": "₹3-6 LPA",
  "Finance Associate": "₹3-6 LPA",
  "Tax Assistant": "₹3-5 LPA",
  "Audit Assistant": "₹3-6 LPA",
  "Accounts Assistant": "₹2.5-5 LPA",
  "Finance Executive": "₹4-7 LPA",
  "Banking Associate": "₹3-6 LPA",
  "Tax Associate": "₹3-6 LPA",
  Accountant: "₹3-7 LPA",
  "Tax Consultant": "₹5-10 LPA",
  "Fintech Associate": "₹5-10 LPA",
  // Arts & Humanities
  "Content Associate": "₹3-6 LPA",
  "Public Policy Assistant": "₹3-6 LPA",
  "Research Assistant": "₹3-5 LPA",
  "Civil Services Aspirant": "Cadre-based pay",
  "Content Strategist": "₹5-10 LPA",
  Teacher: "₹3-7 LPA",
  Editor: "₹4-8 LPA",
  "Research Associate": "₹3-6 LPA",
  "Social Researcher": "₹3-6 LPA",
  "Program Associate": "₹3-6 LPA",
  "Community Manager": "₹4-7 LPA",
  "Policy Assistant": "₹3-6 LPA",
  "Economic Analyst": "₹5-10 LPA",
  Journalist: "₹3-7 LPA",
  "PR Executive": "₹3-6 LPA",
  "Media Planner": "₹4-8 LPA",
  "Public Affairs Associate": "₹3-6 LPA",
  // Data Science & Analytics
  "Data Scientist": "₹6-14 LPA",
  "Machine Learning Engineer": "₹8-16 LPA",
  Statistician: "₹5-10 LPA",
  Actuary: "₹7-15 LPA",
};

export function formatFee(value: number) {
  return `₹${value.toLocaleString("en-IN")}`;
}

