export type CountryCode = { name: string; iso2: string; dial: string };

// India first (primary audience), then alphabetical by name. Dial codes follow ITU-T E.164
// country calling codes; a handful of countries that share the +1 NANP code (Canada, Caribbean
// nations, etc.) are listed individually since the dropdown groups by country name, not by code.
export const COUNTRY_CODES: CountryCode[] = [
  { name: "India", iso2: "IN", dial: "+91" },
  { name: "Afghanistan", iso2: "AF", dial: "+93" },
  { name: "Albania", iso2: "AL", dial: "+355" },
  { name: "Algeria", iso2: "DZ", dial: "+213" },
  { name: "Argentina", iso2: "AR", dial: "+54" },
  { name: "Armenia", iso2: "AM", dial: "+374" },
  { name: "Australia", iso2: "AU", dial: "+61" },
  { name: "Austria", iso2: "AT", dial: "+43" },
  { name: "Azerbaijan", iso2: "AZ", dial: "+994" },
  { name: "Bahrain", iso2: "BH", dial: "+973" },
  { name: "Bangladesh", iso2: "BD", dial: "+880" },
  { name: "Belarus", iso2: "BY", dial: "+375" },
  { name: "Belgium", iso2: "BE", dial: "+32" },
  { name: "Bhutan", iso2: "BT", dial: "+975" },
  { name: "Bolivia", iso2: "BO", dial: "+591" },
  { name: "Bosnia and Herzegovina", iso2: "BA", dial: "+387" },
  { name: "Brazil", iso2: "BR", dial: "+55" },
  { name: "Brunei", iso2: "BN", dial: "+673" },
  { name: "Bulgaria", iso2: "BG", dial: "+359" },
  { name: "Cambodia", iso2: "KH", dial: "+855" },
  { name: "Cameroon", iso2: "CM", dial: "+237" },
  { name: "Canada", iso2: "CA", dial: "+1" },
  { name: "Chile", iso2: "CL", dial: "+56" },
  { name: "China", iso2: "CN", dial: "+86" },
  { name: "Colombia", iso2: "CO", dial: "+57" },
  { name: "Costa Rica", iso2: "CR", dial: "+506" },
  { name: "Croatia", iso2: "HR", dial: "+385" },
  { name: "Cyprus", iso2: "CY", dial: "+357" },
  { name: "Czech Republic", iso2: "CZ", dial: "+420" },
  { name: "Denmark", iso2: "DK", dial: "+45" },
  { name: "Ecuador", iso2: "EC", dial: "+593" },
  { name: "Egypt", iso2: "EG", dial: "+20" },
  { name: "Estonia", iso2: "EE", dial: "+372" },
  { name: "Ethiopia", iso2: "ET", dial: "+251" },
  { name: "Fiji", iso2: "FJ", dial: "+679" },
  { name: "Finland", iso2: "FI", dial: "+358" },
  { name: "France", iso2: "FR", dial: "+33" },
  { name: "Georgia", iso2: "GE", dial: "+995" },
  { name: "Germany", iso2: "DE", dial: "+49" },
  { name: "Ghana", iso2: "GH", dial: "+233" },
  { name: "Greece", iso2: "GR", dial: "+30" },
  { name: "Hong Kong", iso2: "HK", dial: "+852" },
  { name: "Hungary", iso2: "HU", dial: "+36" },
  { name: "Iceland", iso2: "IS", dial: "+354" },
  { name: "Indonesia", iso2: "ID", dial: "+62" },
  { name: "Iran", iso2: "IR", dial: "+98" },
  { name: "Iraq", iso2: "IQ", dial: "+964" },
  { name: "Ireland", iso2: "IE", dial: "+353" },
  { name: "Israel", iso2: "IL", dial: "+972" },
  { name: "Italy", iso2: "IT", dial: "+39" },
  { name: "Jamaica", iso2: "JM", dial: "+1876" },
  { name: "Japan", iso2: "JP", dial: "+81" },
  { name: "Jordan", iso2: "JO", dial: "+962" },
  { name: "Kazakhstan", iso2: "KZ", dial: "+7" },
  { name: "Kenya", iso2: "KE", dial: "+254" },
  { name: "Kuwait", iso2: "KW", dial: "+965" },
  { name: "Kyrgyzstan", iso2: "KG", dial: "+996" },
  { name: "Laos", iso2: "LA", dial: "+856" },
  { name: "Latvia", iso2: "LV", dial: "+371" },
  { name: "Lebanon", iso2: "LB", dial: "+961" },
  { name: "Libya", iso2: "LY", dial: "+218" },
  { name: "Lithuania", iso2: "LT", dial: "+370" },
  { name: "Luxembourg", iso2: "LU", dial: "+352" },
  { name: "Malaysia", iso2: "MY", dial: "+60" },
  { name: "Maldives", iso2: "MV", dial: "+960" },
  { name: "Malta", iso2: "MT", dial: "+356" },
  { name: "Mauritius", iso2: "MU", dial: "+230" },
  { name: "Mexico", iso2: "MX", dial: "+52" },
  { name: "Moldova", iso2: "MD", dial: "+373" },
  { name: "Mongolia", iso2: "MN", dial: "+976" },
  { name: "Montenegro", iso2: "ME", dial: "+382" },
  { name: "Morocco", iso2: "MA", dial: "+212" },
  { name: "Myanmar", iso2: "MM", dial: "+95" },
  { name: "Nepal", iso2: "NP", dial: "+977" },
  { name: "Netherlands", iso2: "NL", dial: "+31" },
  { name: "New Zealand", iso2: "NZ", dial: "+64" },
  { name: "Nigeria", iso2: "NG", dial: "+234" },
  { name: "North Macedonia", iso2: "MK", dial: "+389" },
  { name: "Norway", iso2: "NO", dial: "+47" },
  { name: "Oman", iso2: "OM", dial: "+968" },
  { name: "Pakistan", iso2: "PK", dial: "+92" },
  { name: "Panama", iso2: "PA", dial: "+507" },
  { name: "Papua New Guinea", iso2: "PG", dial: "+675" },
  { name: "Paraguay", iso2: "PY", dial: "+595" },
  { name: "Peru", iso2: "PE", dial: "+51" },
  { name: "Philippines", iso2: "PH", dial: "+63" },
  { name: "Poland", iso2: "PL", dial: "+48" },
  { name: "Portugal", iso2: "PT", dial: "+351" },
  { name: "Qatar", iso2: "QA", dial: "+974" },
  { name: "Romania", iso2: "RO", dial: "+40" },
  { name: "Russia", iso2: "RU", dial: "+7" },
  { name: "Rwanda", iso2: "RW", dial: "+250" },
  { name: "Saudi Arabia", iso2: "SA", dial: "+966" },
  { name: "Serbia", iso2: "RS", dial: "+381" },
  { name: "Singapore", iso2: "SG", dial: "+65" },
  { name: "Slovakia", iso2: "SK", dial: "+421" },
  { name: "Slovenia", iso2: "SI", dial: "+386" },
  { name: "South Africa", iso2: "ZA", dial: "+27" },
  { name: "South Korea", iso2: "KR", dial: "+82" },
  { name: "Spain", iso2: "ES", dial: "+34" },
  { name: "Sri Lanka", iso2: "LK", dial: "+94" },
  { name: "Sweden", iso2: "SE", dial: "+46" },
  { name: "Switzerland", iso2: "CH", dial: "+41" },
  { name: "Taiwan", iso2: "TW", dial: "+886" },
  { name: "Tajikistan", iso2: "TJ", dial: "+992" },
  { name: "Tanzania", iso2: "TZ", dial: "+255" },
  { name: "Thailand", iso2: "TH", dial: "+66" },
  { name: "Trinidad and Tobago", iso2: "TT", dial: "+1868" },
  { name: "Tunisia", iso2: "TN", dial: "+216" },
  { name: "Turkey", iso2: "TR", dial: "+90" },
  { name: "Turkmenistan", iso2: "TM", dial: "+993" },
  { name: "Uganda", iso2: "UG", dial: "+256" },
  { name: "Ukraine", iso2: "UA", dial: "+380" },
  { name: "United Arab Emirates", iso2: "AE", dial: "+971" },
  { name: "United Kingdom", iso2: "GB", dial: "+44" },
  { name: "United States", iso2: "US", dial: "+1" },
  { name: "Uruguay", iso2: "UY", dial: "+598" },
  { name: "Uzbekistan", iso2: "UZ", dial: "+998" },
  { name: "Venezuela", iso2: "VE", dial: "+58" },
  { name: "Vietnam", iso2: "VN", dial: "+84" },
  { name: "Yemen", iso2: "YE", dial: "+967" },
  { name: "Zambia", iso2: "ZM", dial: "+260" },
  { name: "Zimbabwe", iso2: "ZW", dial: "+263" },
];

export const DEFAULT_COUNTRY = COUNTRY_CODES[0]; // India

/** IANA timezone -> ISO2. A device's configured timezone tracks its owner's actual physical
 * location far more reliably than its UI language does -- most people never change their OS
 * display language away from whatever it shipped with (commonly "en-US" regardless of where they
 * actually live), but they do live somewhere with a real, correct timezone. Covers every country
 * in COUNTRY_CODES, plus every additional zone for multi-zone countries (US, Russia, Canada,
 * Australia, Brazil) so those don't all collapse onto one city's zone. */
const TIMEZONE_TO_ISO2: Record<string, string> = {
  "Asia/Kolkata": "IN", "Asia/Calcutta": "IN",
  "Asia/Kabul": "AF",
  "Europe/Tirane": "AL",
  "Africa/Algiers": "DZ",
  "America/Argentina/Buenos_Aires": "AR",
  "Asia/Yerevan": "AM",
  "Australia/Sydney": "AU", "Australia/Melbourne": "AU", "Australia/Brisbane": "AU", "Australia/Perth": "AU", "Australia/Adelaide": "AU", "Australia/Darwin": "AU", "Australia/Hobart": "AU",
  "Europe/Vienna": "AT",
  "Asia/Baku": "AZ",
  "Asia/Bahrain": "BH",
  "Asia/Dhaka": "BD",
  "Europe/Minsk": "BY",
  "Europe/Brussels": "BE",
  "Asia/Thimphu": "BT",
  "America/La_Paz": "BO",
  "Europe/Sarajevo": "BA",
  "America/Sao_Paulo": "BR", "America/Manaus": "BR", "America/Fortaleza": "BR", "America/Rio_Branco": "BR",
  "Asia/Brunei": "BN",
  "Europe/Sofia": "BG",
  "Asia/Phnom_Penh": "KH",
  "Africa/Douala": "CM",
  "America/Toronto": "CA", "America/Vancouver": "CA", "America/Edmonton": "CA", "America/Winnipeg": "CA", "America/Halifax": "CA", "America/St_Johns": "CA",
  "America/Santiago": "CL",
  "Asia/Shanghai": "CN", "Asia/Urumqi": "CN",
  "America/Bogota": "CO",
  "America/Costa_Rica": "CR",
  "Europe/Zagreb": "HR",
  "Asia/Nicosia": "CY",
  "Europe/Prague": "CZ",
  "Europe/Copenhagen": "DK",
  "America/Guayaquil": "EC",
  "Africa/Cairo": "EG",
  "Europe/Tallinn": "EE",
  "Africa/Addis_Ababa": "ET",
  "Pacific/Fiji": "FJ",
  "Europe/Helsinki": "FI",
  "Europe/Paris": "FR",
  "Asia/Tbilisi": "GE",
  "Europe/Berlin": "DE",
  "Africa/Accra": "GH",
  "Europe/Athens": "GR",
  "Asia/Hong_Kong": "HK",
  "Europe/Budapest": "HU",
  "Atlantic/Reykjavik": "IS",
  "Asia/Jakarta": "ID",
  "Asia/Tehran": "IR",
  "Asia/Baghdad": "IQ",
  "Europe/Dublin": "IE",
  "Asia/Jerusalem": "IL",
  "Europe/Rome": "IT",
  "America/Jamaica": "JM",
  "Asia/Tokyo": "JP",
  "Asia/Amman": "JO",
  "Asia/Almaty": "KZ", "Asia/Aqtobe": "KZ",
  "Africa/Nairobi": "KE",
  "Asia/Kuwait": "KW",
  "Asia/Bishkek": "KG",
  "Asia/Vientiane": "LA",
  "Europe/Riga": "LV",
  "Asia/Beirut": "LB",
  "Africa/Tripoli": "LY",
  "Europe/Vilnius": "LT",
  "Europe/Luxembourg": "LU",
  "Asia/Kuala_Lumpur": "MY",
  "Indian/Maldives": "MV",
  "Europe/Malta": "MT",
  "Indian/Mauritius": "MU",
  "America/Mexico_City": "MX", "America/Tijuana": "MX", "America/Cancun": "MX",
  "Europe/Chisinau": "MD",
  "Asia/Ulaanbaatar": "MN",
  "Europe/Podgorica": "ME",
  "Africa/Casablanca": "MA",
  "Asia/Yangon": "MM",
  "Asia/Kathmandu": "NP",
  "Europe/Amsterdam": "NL",
  "Pacific/Auckland": "NZ",
  "Africa/Lagos": "NG",
  "Europe/Skopje": "MK",
  "Europe/Oslo": "NO",
  "Asia/Muscat": "OM",
  "Asia/Karachi": "PK",
  "America/Panama": "PA",
  "Pacific/Port_Moresby": "PG",
  "America/Asuncion": "PY",
  "America/Lima": "PE",
  "Asia/Manila": "PH",
  "Europe/Warsaw": "PL",
  "Europe/Lisbon": "PT",
  "Asia/Qatar": "QA",
  "Europe/Bucharest": "RO",
  "Europe/Moscow": "RU", "Asia/Yekaterinburg": "RU", "Asia/Novosibirsk": "RU", "Asia/Vladivostok": "RU", "Asia/Kamchatka": "RU",
  "Africa/Kigali": "RW",
  "Asia/Riyadh": "SA",
  "Europe/Belgrade": "RS",
  "Asia/Singapore": "SG",
  "Europe/Bratislava": "SK",
  "Europe/Ljubljana": "SI",
  "Africa/Johannesburg": "ZA",
  "Asia/Seoul": "KR",
  "Europe/Madrid": "ES",
  "Asia/Colombo": "LK",
  "Europe/Stockholm": "SE",
  "Europe/Zurich": "CH",
  "Asia/Taipei": "TW",
  "Asia/Dushanbe": "TJ",
  "Africa/Dar_es_Salaam": "TZ",
  "Asia/Bangkok": "TH",
  "America/Port_of_Spain": "TT",
  "Africa/Tunis": "TN",
  "Europe/Istanbul": "TR",
  "Asia/Ashgabat": "TM",
  "Africa/Kampala": "UG",
  "Europe/Kyiv": "UA",
  "Asia/Dubai": "AE",
  "Europe/London": "GB",
  "America/New_York": "US", "America/Chicago": "US", "America/Denver": "US", "America/Los_Angeles": "US", "America/Anchorage": "US", "Pacific/Honolulu": "US", "America/Phoenix": "US",
  "America/Montevideo": "UY",
  "Asia/Tashkent": "UZ",
  "America/Caracas": "VE",
  "Asia/Ho_Chi_Minh": "VN",
  "Asia/Aden": "YE",
  "Africa/Lusaka": "ZM",
  "Africa/Harare": "ZW",
};

/** Maps a BCP-47 locale tag (e.g. "en-IN", "en-US") to a country by its region subtag. Falls
 * back to India, this site's primary audience, when the locale carries no usable region (e.g.
 * a bare "en" with no subtag, or a browser exposing no `navigator.language` at all). */
export function countryFromLocale(locale: string | undefined | null): CountryCode {
  const region = locale?.split(/[-_]/)[1]?.toUpperCase();
  return COUNTRY_CODES.find((country) => country.iso2 === region) ?? DEFAULT_COUNTRY;
}

/** Maps the device's configured IANA timezone (e.g. "Asia/Kolkata") to a country. This is the
 * preferred signal over `countryFromLocale` -- a browser's UI language is very often left as
 * whatever the OS shipped with regardless of where the person actually lives, but the timezone
 * tracks real physical location for almost everyone. Falls back to India when the zone isn't in
 * the table (rare -- covers every country this dropdown lists). */
export function countryFromTimezone(timezone: string | undefined | null): CountryCode {
  const iso2 = timezone ? TIMEZONE_TO_ISO2[timezone] : undefined;
  return COUNTRY_CODES.find((country) => country.iso2 === iso2) ?? DEFAULT_COUNTRY;
}

export function countryByDial(dial: string): CountryCode | undefined {
  return COUNTRY_CODES.find((country) => country.dial === dial);
}

/** Renders a country's flag from its ISO2 code using the two matching Unicode Regional Indicator
 * Symbols -- no image assets or emoji data needed, works for every real ISO2 code. */
export function flagEmoji(iso2: string) {
  return iso2
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}
