"use client";
import { useEffect,useState,useRef } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/providers/auth-provider';
import { canUseApplications } from '@/lib/application-access';
import { useModuleEnabled } from '@/components/auth/feature-gate';
import { apiFetch } from '@/lib/api';
import { PageHeader } from '@/components/layout/page-header';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card } from '@/components/ui/card';
import { StandardDialog } from '@/components/common/standard-dialog';
import { ErrorState } from '@/components/common/error-state';
import { ApplicationSelect,applicationErrorMessage } from '@/components/applications/fields';
import { useRetainedEditorDraft } from '@/providers/editor-draft-provider';
import { useEditorDismissGuard } from '@/hooks/use-editor-dismiss-guard';
import { formatWorkspaceDateTime } from '@/lib/date-format';
const EMPTY={leadId:'',programId:'',stageId:'',courseId:'',intakeId:'',opportunityId:'',requestKey:''};
export default function ApplicationsPage(){
 const {user,isLoading}=useAuth();const enabled=useModuleEnabled('PRODUCT_CATALOG');const allowed=canUseApplications(user,'read')&&enabled;const router=useRouter();
 const [search,setSearch]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState<any[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[open,setOpen]=useState(false);
 const {draft,update,current}=useRetainedEditorDraft('application:create');const form:typeof EMPTY=draft.values?.form??EMPTY;
 const setField=(key:keyof typeof EMPTY,value:string)=>update({values:{form:{...form,[key]:value,...(key==='programId'?{stageId:'',courseId:'',intakeId:'',opportunityId:''}:key==='leadId'?{opportunityId:''}:{})}},dirty:true});
 const canDismiss=useEditorDismissGuard(open&&draft.dirty,open&&draft.pending,()=>update({values:null,dirty:false,error:''}));const close=()=>{if(canDismiss())setOpen(false);};
 const [leadSearch,setLeadSearch]=useState(''),[options,setOptions]=useState<any>({leads:[],programs:[],stages:[],courses:[],intakes:[],opportunities:[]}),[optionError,setOptionError]=useState(''),[optionsLoading,setOptionsLoading]=useState(false),[optionAttempt,setOptionAttempt]=useState(0);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!allowed)return;const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>apiFetch<any>(`/applications?search=${encodeURIComponent(search)}&page=${page}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setRows(result.data);setTotal(result.total);}}).catch(error=>{if(!controller.signal.aborted)setError(applicationErrorMessage(error));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);}),200);return()=>{clearTimeout(timer);controller.abort();};},[allowed,search,page,attempt]);
 useEffect(()=>{if(!open||!allowed)return;const controller=new AbortController();setOptionsLoading(true);setOptionError('');const timer=setTimeout(()=>apiFetch<any>(`/applications/options?search=${encodeURIComponent(leadSearch)}&programId=${encodeURIComponent(form.programId)}&leadId=${encodeURIComponent(form.leadId)}`,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setOptions(value);}).catch(error=>{if(!controller.signal.aborted)setOptionError(applicationErrorMessage(error));}).finally(()=>{if(!controller.signal.aborted)setOptionsLoading(false);}),200);return()=>{clearTimeout(timer);controller.abort();};},[open,allowed,leadSearch,form.programId,form.leadId,optionAttempt]);
 const create=async()=>{if(current().pending)return;update({pending:true,error:''});try{const result=await apiFetch<any>('/applications',{method:'POST',body:JSON.stringify({...form,courseId:form.courseId||null,intakeId:form.intakeId||null,opportunityId:form.opportunityId||null})});update({values:null,dirty:false,error:''});if(alive.current){setOpen(false);router.push('/dashboard/applications/'+result.id);}}catch(error){update({error:applicationErrorMessage(error)});}finally{update({pending:false});}};
 if(isLoading)return <p role="status">Loading applications…</p>;
 if(!allowed)return <ErrorState description={enabled?'You do not have Applications read permission.':'Product Catalog and Applications is disabled for this workspace.'}/>;
 return <div className="min-w-0 space-y-4"><PageHeader title="Applications" description="Track applicants by university, program and intake." actions={<>{canUseApplications(user,'manage')&&<Button className="h-auto min-h-10 max-w-full whitespace-normal break-words" variant="outline" asChild><Link href="/dashboard/applications/numbering">Numbering rules</Link></Button>}{canUseApplications(user,'create')&&<Button className="h-auto min-h-10 max-w-full whitespace-normal break-words" onClick={()=>{if(!current().values)update({values:{form:{...EMPTY,requestKey:crypto.randomUUID()}},dirty:false,error:''});setOpen(true);}}>New Application</Button>}</>}/>
 <div className="max-w-lg space-y-2"><Label htmlFor="application-search">Search applications</Label><Input id="application-search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Application number, applicant or program"/></div>
 {loading?<p role="status">Loading applications…</p>:error?<ErrorState description={error} onRetry={()=>setAttempt(n=>n+1)}/>:<><p className="text-sm text-muted-foreground">{total} applications</p>{!rows.length?<Card className="p-6"><p>No applications match this search.</p><p className="mt-1 text-sm text-muted-foreground">Configure a program and open application stage in Catalog before creating an application.</p></Card>:<div className="grid min-w-0 gap-3 lg:grid-cols-2">{rows.map(row=><Card key={row.id} className="min-w-0 space-y-2 p-4"><Link className="break-words font-semibold text-primary underline-offset-4 hover:underline" href={'/dashboard/applications/'+row.id}>{row.applicationNumber}</Link><p className="break-words">{row.applicantName||'Applicant unavailable'}</p><p className="break-words text-sm text-muted-foreground">{row.universityName} · {row.programName}</p><p className="break-words text-sm">{row.stageName}{row.intakeName?' · '+row.intakeName:''}</p><p className="text-xs text-muted-foreground">{formatWorkspaceDateTime(row.createdAt)}</p></Card>)}</div>}<div className="flex flex-wrap items-center gap-3"><Button className="h-auto min-h-10 max-w-full whitespace-normal break-words" variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>Page {page} of {Math.max(1,Math.ceil(total/25))}</span><Button className="h-auto min-h-10 max-w-full whitespace-normal break-words" variant="outline" disabled={page*25>=total} onClick={()=>setPage(p=>p+1)}>Next</Button></div></>}
 <StandardDialog open={open} onClose={close} title="New Application" subtitle="The application number is assigned when you save." actions={<><Button className="h-auto min-h-10 max-w-full whitespace-normal break-words" variant="outline" disabled={draft.pending} onClick={close}>Cancel</Button><Button className="h-auto min-h-10 max-w-full whitespace-normal break-words" disabled={draft.pending||optionsLoading||!!optionError||!form.leadId||!form.programId||!form.stageId} onClick={create}>{draft.pending?'Creating…':'Create Application'}</Button></>}>
 <fieldset disabled={draft.pending} className="min-w-0 space-y-4">{draft.dirty&&<p className="text-xs text-muted-foreground">This draft is kept during navigation. Refreshing or signing out clears it.</p>}<div className="space-y-2"><Label htmlFor="applicant-search">Find applicant</Label><Input id="applicant-search" value={leadSearch} onChange={e=>setLeadSearch(e.target.value)} placeholder="Search Lead names"/><p className="text-xs text-muted-foreground">Showing up to 50 accessible Leads. Search to narrow the list.</p></div>
 {optionError?<ErrorState description={optionError} onRetry={()=>setOptionAttempt(n=>n+1)}/>:null}{optionsLoading&&<p role="status" className="text-sm">Loading available choices…</p>}
 <ApplicationSelect id="application-lead" label="Applicant (Lead)" value={form.leadId} onChange={v=>setField('leadId',v)} items={options.leads}/>
 <ApplicationSelect id="application-program" label="Program" value={form.programId} onChange={v=>setField('programId',v)} items={options.programs.map((p:any)=>({id:p.id,name:p.universityName+' — '+p.name}))}/>
 <ApplicationSelect id="application-stage" label="Initial stage" value={form.stageId} onChange={v=>setField('stageId',v)} items={options.stages} disabled={!form.programId||optionsLoading}/>
 <ApplicationSelect id="application-course" label="Course (optional)" value={form.courseId} onChange={v=>setField('courseId',v)} items={options.courses} optional disabled={!form.programId||optionsLoading}/>
 <ApplicationSelect id="application-intake" label="Intake (optional)" value={form.intakeId} onChange={v=>setField('intakeId',v)} items={options.intakes} optional disabled={!form.programId||optionsLoading}/>
 <ApplicationSelect id="application-opportunity" label="Linked opportunity (optional)" value={form.opportunityId} onChange={v=>setField('opportunityId',v)} items={options.opportunities} optional disabled={!form.programId||!form.leadId||optionsLoading}/>
 {form.programId&&!optionsLoading&&!options.stages.length&&<p role="alert" className="text-sm">No open application stages are configured for this program. Ask a catalog administrator to add one.</p>}{draft.error&&<p role="alert" className="break-words text-sm text-destructive">{draft.error}</p>}
 </fieldset></StandardDialog></div>;
}
