/** Local-only integration smoke. Creates and removes isolated catalog/application fixtures. */
import { createRequire } from 'module';
import { randomUUID } from 'crypto';
import assert from 'node:assert/strict';
import { createApplication,getApplication,listApplications,saveNumberingRule,transitionApplication,getApplicationWorkflow } from '../src/lib/repositories/applications-postgres';
import { getPool } from '../src/lib/db/pool';
const require=createRequire(import.meta.url);
const d=require('./db-utils.js');
async function main(){
 for(const url of [d.directDatabaseUrl(),d.appDatabaseUrl()])assert.ok(['localhost','127.0.0.1'].includes(new URL(url).hostname),'Local database required');
 const pool=getPool();const q=(sql:string,args:unknown[]=[])=>pool.query(sql,args);
 const user=(await q('select id,"tenantId" from "User" where email=$1',['admintest@test.com'])).rows[0];assert.ok(user);const actor={...user,isTenantAdmin:true};
 const lead=(await q('select id from "Lead" where "tenantId"=$1 limit 1',[user.tenantId])).rows[0];assert.ok(lead,'A local applicant fixture is required');
 const catalog=randomUUID(),university=randomUUID(),program=randomUUID(),stage=randomUUID();let checks=0;
 const check=(v:unknown)=>{assert.ok(v);checks++;};
 try{
 await q('insert into "ProductCatalog" (id,"tenantId",name) values ($1,$2,$3)',[catalog,user.tenantId,'Application smoke']);
 await q('insert into "University" (id,"tenantId","catalogId",name) values ($1,$2,$3,$4)',[university,user.tenantId,catalog,'Application smoke university']);
 await q('insert into "Program" (id,"tenantId","universityId",name) values ($1,$2,$3,$4)',[program,user.tenantId,university,'Application smoke program']);
 await q('insert into "ApplicationStage" (id,"tenantId","programId",name) values ($1,$2,$3,$4)',[stage,user.tenantId,program,'New']);
 const rule=await saveNumberingRule(actor,{universityId:university,prefix:'SMOKE-{FY}-'});
 check(rule.prefix==='SMOKE-{FY}-');
 const edited=await saveNumberingRule(actor,{universityId:university,prefix:'SMOKE-{YYYY}-'});check(edited.id===rule.id);
 const input={leadId:lead.id,programId:program,stageId:stage,requestKey:randomUUID()};
 const duplicates=await Promise.all(Array.from({length:6},()=>createApplication(actor,input)));
 check(new Set(duplicates.map(r=>r.record.id)).size===1);check(duplicates.filter(r=>!r.replayed).length===1);
 const distinct=await Promise.all(Array.from({length:6},()=>createApplication(actor,{...input,requestKey:randomUUID()})));
 check(new Set(distinct.map(r=>r.record.applicationNumber)).size===6);check(distinct.every(r=>r.record.applicationNumber.startsWith('SMOKE-')));
 await assert.rejects(()=>createApplication(actor,{...input,courseId:'invalid'}),(e:any)=>e.status===409);checks++;
 await assert.rejects(()=>createApplication(actor,{...input,requestKey:randomUUID(),stageId:'invalid'}),(e:any)=>e.status===400);checks++;
 await assert.rejects(()=>createApplication(actor,{...input,requestKey:randomUUID(),leadId:'invalid'}),(e:any)=>e.status===400);checks++;
 const id=duplicates[0].record.id;
 check(await getApplication({...actor,tenantId:randomUUID()},id)===null);
 const own={...user,id:randomUUID(),role:{permissions:{recordAccess:'OWN',modules:{applications:{read:true}}}}};
 check(await getApplication(own,id)===null);check((await listApplications(own,'Application smoke',1)).total===0);
 await assert.rejects(()=>createApplication(own,input),(e:any)=>e.status===403);checks++;
 check(Number((await q('select count(*) from "ApplicationStageHistory" where "applicationId"=$1',[id])).rows[0].count)===1);
 check(Number((await q('select count(*) from "AuditLog" where "entityId"=$1',[id])).rows[0].count)===1);

 const guarded=randomUUID(),closed=randomUUID(),checklist=randomUUID(),document=randomUUID();
 await q('insert into "ApplicationStage" (id,"tenantId","programId",name,"requiresVerifiedDocuments") values ($1,$2,$3,$4,true)',[guarded,user.tenantId,program,'Review']);
 await q('insert into "ApplicationStage" (id,"tenantId","programId",name,"isClosed") values ($1,$2,$3,$4,true)',[closed,user.tenantId,program,'Closed']);
 await q('insert into "ApplicationChecklist" (id,"tenantId","programId",name) values ($1,$2,$3,$4)',[checklist,user.tenantId,program,'Transcript']);
 const change={expectedStageId:stage,stageId:guarded,reason:'Document review completed'};
 const status=async()=>(await getApplicationWorkflow(actor,id)).checklist[0].status;
 check(await status()==='MISSING');
 await assert.rejects(()=>transitionApplication(actor,id,change),(e:any)=>e.status===409);checks++;
 await assert.rejects(()=>createApplication(actor,{...input,requestKey:randomUUID(),stageId:guarded}),(e:any)=>e.status===400);checks++;
 await q('insert into "ApplicationDocument" (id,"tenantId","applicationId","checklistItemId",name,"uploadStatus","fileStoragePath") values ($1,$2,$3,$4,$5,$6,$7)',[document,user.tenantId,id,checklist,'Test transcript','UPLOADED','test-only/no-real-file']);
 check(await status()==='PENDING');
 await q('update "ApplicationDocument" set "verificationStatus"=$2,"rejectionReason"=$3 where id=$1',[document,'REJECTED','Unreadable']);
 check(await status()==='REJECTED');
 await assert.rejects(()=>transitionApplication(actor,id,change),(e:any)=>e.status===409);checks++;
 await q('update "ApplicationDocument" set "verificationStatus"=$2,"reviewerId"=$3,"verifiedAt"=now(),"expiryDate"=current_date-1 where id=$1',[document,'VERIFIED',user.id]);
 check(await status()==='EXPIRED');
 await assert.rejects(()=>transitionApplication(actor,id,change),(e:any)=>e.status===409);checks++;
 await q('update "ApplicationDocument" set "expiryDate"=current_date+1 where id=$1',[document]);
 check(await status()==='VERIFIED');
 const replacement=randomUUID();
 await q(`insert into "ApplicationDocument" (id,"tenantId","applicationId","checklistItemId",name,"uploadStatus","verificationStatus","updatedAt") values ($1,$2,$3,$4,$5,$6,$7,now()+interval '1 second')`,[replacement,user.tenantId,id,checklist,'Replacement','UPLOADED','REJECTED']);
 check(await status()==='REJECTED');
 await assert.rejects(()=>transitionApplication(actor,id,change),(e:any)=>e.status===409);checks++;
 await q(`update "ApplicationDocument" set "updatedAt"=now()+interval '2 seconds' where id=$1`,[document]);
 check(await status()==='REJECTED');
 await q('delete from "ApplicationDocument" where id=$1',[replacement]);
 await assert.rejects(()=>transitionApplication({...actor,tenantId:randomUUID()},id,change),(e:any)=>e.status===404);checks++;
 await assert.rejects(()=>transitionApplication(own,id,change),(e:any)=>e.status===403);checks++;
 const restricted={...user,role:{permissions:{recordAccess:'OWN',modules:{applications:{read:true,update:true}}}}};
 await assert.rejects(()=>transitionApplication(restricted,id,{...change,stageId:closed}),(e:any)=>e.status===403);checks++;
 const attempts=await Promise.allSettled(Array.from({length:6},()=>transitionApplication(actor,id,change)));
 for(const result of attempts)if(result.status==='rejected')throw result.reason;
 const moves=attempts.map(result=>(result as PromiseFulfilledResult<any>).value);
 check(moves.every(r=>r.stageId===guarded));
 check(Number((await q('select count(*) from "ApplicationStageHistory" where "applicationId"=$1',[id])).rows[0].count)===2);
 check(Number((await q('select count(*) from "AuditLog" where "entityId"=$1',[id])).rows[0].count)===2);
 await assert.rejects(()=>transitionApplication(actor,id,{...change,stageId:closed}),(e:any)=>e.status===409);checks++;
 await assert.rejects(()=>transitionApplication(actor,id,{...change,expectedStageId:guarded,stageId:randomUUID()}),(e:any)=>e.status===400);checks++;
 await transitionApplication(actor,id,{expectedStageId:guarded,stageId:closed,reason:'Applicant withdrew'});
 await assert.rejects(()=>transitionApplication(restricted,id,{expectedStageId:closed,stageId:stage,reason:'Reopen application'}),(e:any)=>e.status===403);checks++;
 const reopened=await transitionApplication(actor,id,{expectedStageId:closed,stageId:stage,reason:'Authorized reopening'});check(reopened.stageId===stage);
 console.log(JSON.stringify({checks,status:'passed',concurrentSameRequest:6,concurrentDistinctRequests:6}));
 }finally{
 await q('delete from "AuditLog" where "tenantId"=$1 and ("entityId" in (select id from "Application" where "programId"=$2) or "entityId" in (select id from "ApplicationNumberRule" where "universityId"=$3))',[user.tenantId,program,university]);
 await q('delete from "ApplicationStageHistory" where "applicationId" in (select id from "Application" where "programId"=$1)',[program]);
 await q('delete from "Application" where "programId"=$1',[program]);
 await q('delete from "ApplicationNumberRule" where "universityId"=$1',[university]);
 await q('delete from "ApplicationStage" where "programId"=$1',[program]);
 await q('delete from "Program" where id=$1',[program]);await q('delete from "University" where id=$1',[university]);await q('delete from "ProductCatalog" where id=$1',[catalog]);
 await pool.end();
 }
}
main().catch(e=>{console.error(e.stack);process.exitCode=1;});
